#ifndef SIMULADORCAMADAENLACE_CAMADAENLACE_HPP
#define SIMULADORCAMADAENLACE_CAMADAENLACE_HPP
#include "../base-template.hpp"

/*
    Definições aqui
*/

#endif //SIMULADORCAMADAENLACE_CAMADAENLACE_HPP